import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import localFont from 'next/font/local';
import Nav from '@/components/nav';
import Footer from '@/components/footer';

const pretendard = localFont({
  src: '../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});
const gmarketsansBold = localFont({
  src: '../public/fonts/GmarketSansBold.woff',
  display: 'swap',
  weight: '45 920',
  variable: '--font-gmarketsansBold',
});
const gmarketsansMedium = localFont({
  src: '../public/fonts/GmarketSansMedium.woff',
  display: 'swap',
  weight: '45 920',
  variable: '--font-gmarketsansMedium',
});
const gmarketsansLight = localFont({
  src: '../public/fonts/GmarketSansLight.woff',
  display: 'swap',
  weight: '45 920',
  variable: '--font-gmarketsansLight',
});

const mbc1961 = localFont({
  src: '../public/fonts/MBC1961M.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-mbc1961',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      {/* ${GmarketSansBold.variable} */}
      <body
        className={`${pretendard.variable}  ${gmarketsansBold.variable} ${gmarketsansMedium.variable}  ${gmarketsansLight.variable} ${mbc1961.variable}  font-pretendard`}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
